#ENCODED VALUES
# admin-service: YWRtaW4tc2VydmljZTphZG1pbg==
# admin:    YWRtaW4tc2VydmljZTphZG1pbg==
# ztestowy: enRlc3Rvd3k6MTIz
# jtestowy: anRlc3Rvd3k6MTIz
# mtestowy: bXRlc3Rvd3k6MTIz
# btestowy: YnRlc3Rvd3k6MTIz

#GET ALL KNIVES
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/knives
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET SINGLE KNIFE
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
Authorization: Basic YnRlc3Rvd3k6MTIz
###

#GET NON EXISTING KNIFE - 404 NOT FOUND
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c0
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#CREATE KNIFE
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "TestKnife",
  "bladeLength": 10.0,
  "productionDate": "2020-01-01"
}

###
#DELETE KNIFE
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Authorization: Basic YnRlc3Rvd3k6MTIz

###
#CREATE KNIFE ASSOCIATED WITH EXISTING CATEGORY - NEW LAB4
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "TestKnife",
  "bladeLength": 10.0,
  "productionDate": "2020-01-01"
}

###

#UPDATE KNIFE
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
#Authorization: Basic YnRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "TestKnifeUpdated",
  "bladeLength": 20.0,
  "productionDate": "2020-01-01",
  "category": "c4804e0f-769e-4ab9-9ebe-0578fb4f00b1"
}

###
#DELETE KNIFE
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
Authorization: Basic enRlc3Rvd3k6MTIz
###

#TRY TO UDATE NOT EXISTING KNIFE
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c0
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "TestKnifeUpdated",
  "bladeLength": 20.0,
  "productionDate": "2020-01-01",
  "category": "c4804e0f-769e-4ab9-9ebe-0578fb4f00b1"
}

###

#GET UPDATED KNIFE
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET ALL CATEGORIES
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/categories
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET CATEGORY
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET CATEGORY KNIVES
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1/knives
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET CATEGORY KNIVES - NOT EXISTING CATEGORY
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b0/knives
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET USER KNIVES
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1/knives
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET NON EXISTING USER's KNIVES
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0/knives
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#DELETE CATEGORY
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#CREATE CATEGORY
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "New Knife Category",
  "description": "Great knives"
}

###
#UPDATE CATEGORY
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "Updated Knife Category",
  "description": "Better knives"
}

###
#UPDATE NEW CATEGORY
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "Updated Knife Category",
  "description": "Great knives"
}
###
#TRY TO UPDATE NON EXISTING CATEGORY
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b0
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "Updated Knife Category",
  "description": "Better knives"
}

###

#CREATE KNIFE ASSOCIATED WITH THE NEW CATEGORY
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b9/knives/c4804e0f-769e-4ab9-9ebe-0578fb4f00c8
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "TestKnife",
  "bladeLength": 10.0,
  "productionDate": "2020-01-01",
  "user": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a1"
}
###

#GET NEW CATEGORY KNIVES
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b9/knives
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET NEW CATEGORY
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#DELETE NEW CATEGORY
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/categories/c4804e0f-769e-4ab9-9ebe-0578fb4f00b9
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz

