#ENCODED VALUES
# admin:    YWRtaW4tc2VydmljZTphZG1pbg==
# ztestowy: enRlc3Rvd3k6MTIz
# jtestowy: anRlc3Rvd3k6MTIz
# mtestowy: bXRlc3Rvd3k6MTIz
# btestowy: YnRlc3Rvd3k6MTIz
# testPodczasLabow: dGVzdFBvZGN6YXNMYWJvdzp0ZXN0MTIz

#GET USERS
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET USER
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1
#Authorization: Basic anRlc3Rvd3k6MTIz=
Authorization: Basic anRlc3Rvd3k6MTIzz
###

#GET NON EXISTING USER - 404 NOT FOUND
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#CREATE USER
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/users/3c6f1eb1-8069-44ab-988f-d7fed2b65d80
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "login": "testPodczasLabow1",
  "name": "Lab",
  "surname": "1",
  "password": "test123",
  "birthDate": "1990-01-01"
}

###

#UPDATE USER
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1
#Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "Updated Name",
  "surname": "Updated Surname",
  "birthDate": "2000-01-01"
}

###

#TRY TO UPDATE NON EXISTING USER - 404 NOT FOUND
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: application/json

{
  "name": "Updated Name",
  "surname": "Updated Surname",
  "birthDate": "2000-01-01"
}

###

#DELETE USER
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#TRY TO DELETE NON EXISTING USER - 404 NOT FOUND
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#CREATE USER's PHOTO
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/users/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo4.jpg"

< /home/student/Dokumenty/188918/JakartaEE-Lab5/knife-store/src/main/resources/photo4.jpg
--boundary--

###

#TRY TO CREATE PHOTO FOR NON EXISTING USER - 404 NOT FOUND
// @no-cookie-jar
PUT http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo4.jpg"

< /home/student/Dokumenty/188918/JakartaEE-Lab5/knife-store/src/main/resources/photo4.jpg
--boundary--

###

#GET CREATED USER's PHOTO
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###


#GET USER's PHOTO
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#GET NON EXISTING USER's PHOTO - 404 NOT FOUND
// @no-cookie-jar
GET http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#DELETE USER's PHOTO
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/users/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#TRY TO DELETE NON EXISTING USER's PHOTO - 404 NOT FOUND
// @no-cookie-jar
DELETE http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
###

#PATCH USER's PHOTO
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/users/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo3.jpg"

< /home/student/Dokumenty/188918/JakartaEE-Lab5/knife-store/src/main/resources/photo3.jpg
--boundary--

###

#PATCH NON EXISTING USER's PHOTO - 404 NOT FOUND
// @no-cookie-jar
PATCH http://localhost:9082/knife-store/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a0/photo
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbg==
#Authorization: Basic enRlc3Rvd3k6MTIz
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo3.jpg"

< D:\Sem7\JakartaEE\Lab1\knife-store\src\main\resources\photo3.jpg
--boundary--

###

